# Generated by Django 4.2.3 on 2024-12-08 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aperator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Viloyat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Royxta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100)),
                ('familya', models.CharField(max_length=100)),
                ('tuman', models.CharField(max_length=100)),
                ('mahhala', models.CharField(max_length=200)),
                ('raqam', models.IntegerField()),
                ('kilent', models.IntegerField()),
                ('aperator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.aperator')),
                ('viloyat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.viloyat')),
            ],
        ),
    ]
