# Generated by Django 4.2.3 on 2024-12-09 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_royxta_royxat_vaqti'),
    ]

    operations = [
        migrations.CreateModel(
            name='Royxat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100)),
                ('familya', models.CharField(max_length=100)),
                ('tuman', models.CharField(max_length=100)),
                ('mahhala', models.CharField(max_length=200)),
                ('raqam', models.IntegerField()),
                ('kilent', models.IntegerField()),
                ('royxat_vaqti', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('RO', 'Royxatga olingan'), ('YT', 'Yetkazib berishga tayyor'), ('YB', 'Yetkazib berildi')], default='RO', max_length=2)),
                ('aperator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.aperator')),
                ('viloyat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.viloyat')),
            ],
        ),
        migrations.DeleteModel(
            name='Royxta',
        ),
    ]
