# Generated by Django 4.2.3 on 2024-12-09 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_royxat_delete_royxta'),
    ]

    operations = [
        migrations.AddField(
            model_name='royxat',
            name='sharx',
            field=models.TextField(null=True),
        ),
    ]
