# Generated by Django 4.2.3 on 2024-12-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_royxat_sharx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='royxat',
            name='status',
            field=models.CharField(choices=[('RO', 'Royxatga olingan'), ('YT', 'Yetkazib berishga tayyor'), ('YB', 'Yetkazib berildi'), ('BK', 'Bekor qilingan')], default='RO', max_length=2),
        ),
    ]
